<a href="https://colab.research.google.com/github/MClaraFerreira5/An-lise-de-Desempenho/blob/main/01_PLN_spaCy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# spaCy

spaCy é uma biblioteca para PLN que se tornado bastante popular nos últimos anos. Ela é mais recente que o NLTK, projetada especificamente para i) trabalhar em problemas maiores e ii) ocultar detalhes irrelevantes para o  usuário. Vamos nos concentrar nos principais recursos:

[Carregando modelos pré-treinados](#loading)<br>

[Tokenization](#tokenization)<br>

[Lemmatization](#lemma)<br>

[Named entity recognition (NER)](#ner)<br>

[Vizualizando NER](#visualize-ner)<br>

[Word vectors e Similaridades](#vectors)<br>

# Instalação

In [4]:
!pip install spacy
!spacy download pt

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.26.8)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.0)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
⚠ As of spaCy v3.0, shortcuts like 'pt' are deprecated. Please use the
full pipeline package name 'pt_core_news_sm' instead.
Collecting pt-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.8.0/pt_core_news_sm-3.8.0-py3-none-any.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 21.0 MB/s eta 0:00:00
Installing collected packages: pt-core-news-sm
Successfully installed pt-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [5]:
import os
import spacy
import numpy as np
import pandas as pd

## Loading spaCy models <a id='loading'></a>

O spaCy disponibiliza uma série de [modelos](https://spacy.io/usage/models) pré-treinados, que devem ser baixados e podem funcionar em problemas mais genéricos. spaCy possui modelos diferentes para diferentes idiomas, inclusive em português.

Para fazer uso dos modelos, primeiro os carregamos no spaCy com

`nlp = spacy.load ('en')`, que armazena o modelo em uma variável chamada nlp para nós. O `'en'` significa inglês. Se você deseja processar dados nesses idiomas, primeiro precisa baixar os modelos relevantes e carregá-los de maneira semelhante.

O modelo aqui referenciado para o português `pt` corresponde a um modelo de CNN treinado em um subconjunto da base WikiNER. Além do `pt_core_news_sm`, o spacy possui o `pt_core_news_md` e o `pt_core_news_lg`. Detalhes das bases utilizadas e acurácia de cada modelo podem ser vistos [aqui](https://spacy.io/models/pt).

In [6]:
nlp = spacy.load('pt_core_news_sm')

O modelo agora pode ser acessado através da variável `nlp`:

In [7]:
doc = nlp("Eu gostaria que as aboboras viessem com mais sementes.")

## Tokenization <a id='tokenization'></a>

A tokenização no spaCy é bem simples de ser utilizada com os modelos pré-treinados. Quando iteramos sobre um objeto `Doc`, spaCy assume que queremos iterar sobre os tokens.

In [8]:
for token in doc:
    print(token)

Eu
gostaria
que
as
aboboras
viessem
com
mais
sementes
.

In [9]:
# quantidade de tokens
len(doc)

10

Cada `token` em `doc` é uma instância da classe `Token`. Este objeto armazena uma série de informações relevantes. como a representação em string do token (`.text`) o índice (`.idx`), ou ainda aspectos linguísticos como `.is_stop`,  `.is_space`, `.lemma_`  e `.pos_`.

In [10]:
for token in doc:
    print("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}".format(
        token.text,
        token.idx,
        token.lemma_,
        token.is_stop,
        token.is_punct,
        token.is_space,
        token.pos_,
        token.dep_,
    ))

Eu	0	eu	True	False	False	PRON	nsubj
gostaria	3	gostar	False	False	False	VERB	ROOT
que	12	que	True	False	False	SCONJ	mark
as	16	o	True	False	False	DET	det
aboboras	19	abobora	False	False	False	NOUN	nsubj
viessem	28	vier	False	False	False	VERB	ccomp
com	36	com	True	False	False	ADP	case
mais	40	mais	True	False	False	ADV	det
sementes	45	semente	False	False	False	NOUN	obl
.	53	.	False	True	False	PUNCT	punct

### Exercício

Verifique a quantidade de tokens considerados stopwords e pontuação do texto abaixo. Imprima uma versão do texto removendo este tipo de tokens

In [11]:
# Texto
review = '''Este é sem dúvida o pior filme que eu já vi. E acredite em mim, eu vi muitos filmes. A reviravolta inacreditável que o filme faz - passando de um extremamente mau filme "Formas de vida alienígenas habitam a terra", com um filme que tenta espalhar um arquicristiano "O dia do julgamento está próximo, buscar Jesus ou queimar por toda a eternidade em as dívidas ardentes do inferno "mensagem - deixou-me atordoado depois de ter sido atormentado por 85 minutos. Até mesmo os cristãos religiosos devem se envergonhar ou ficar furiosos ao ver suas crenças postadas dessa maneira. Eu não sabia o que fazer comigo quando assisti a atuação horrível que poderia ter sido realizada por crianças de 7 anos de idade. Simplesmente repugnante. Eu não sou cristão nem muito religioso. Mas se eu estivesse, não teria mais medo do Inferno. Rich Christiano mostrou ser algo muito pior.'''

# sua resposta
# Usar o modelo nlp para carregar o review
news = nlp(review)

#Tokenizar
print("\nTokens originais:\n")
for token in news:
  print(token)

# Agora vamos verificar a quantidade de stopwords e pontuação de textos
print("\nPropriedades dos tokens (is_stop, is_punct):\n")
for token in news:
  print("{0}\t{1}\t{2}".format(token, token.is_stop, token.is_punct))

print("\nTokens filtrados (sem stopwords e pontuação):\n")

# Criar uma lista com os tokens filtrados
tokens_filtrados = [token.text for token in news if not token.is_stop and not token.is_punct]

for token_text in tokens_filtrados:
  print(token_text)

# Quantidade de stopwords e pontuação
num_stopwords = sum(1 for token in news if token.is_stop)
num_punctuation = sum(1 for token in news if token.is_punct)

print(f"\nNúmero de stopwords: {num_stopwords}")
print(f"Número de pontuação: {num_punctuation}")

Tokens originais:

Este
é
sem
dúvida
o
pior
filme
que
eu
já
vi
.
E
acredite
em
mim
,
eu
vi
muitos
filmes
.
A
reviravolta
inacreditável
que
o
filme
faz
-
passando
de
um
extremamente
mau
filme
"
Formas
de
vida
alienígenas
habitam
a
terra
"
,
com
um
filme
que
tenta
espalhar
um
arquicristiano
"
O
dia
do
julgamento
está
próximo
,
buscar
Jesus
ou
queimar
por
toda
a
eternidade
em
as
dívidas
ardentes
do
inferno
"
mensagem
-
deixou-me
atordoado
depois
de
ter
sido
atormentado
por
85
minutos
.
Até
mesmo
os
cristãos
religiosos
devem
se
envergonhar
ou
ficar
furiosos
ao
ver
suas
crenças
postadas
dessa
maneira
.
Eu
não
sabia
o
que
fazer
comigo
quando
assisti
a
atuação
horrível
que
poderia
ter
sido
realizada
por
crianças
de
7
anos
de
idade
.
Simplesmente
repugnante
.
Eu
não
sou
cristão
nem
muito
religioso
.
Mas
se
eu
estivesse
,
não
teria
mais
medo
do
Inferno
.
Rich
Christiano
mostrou
ser
algo
muito
pior
.

Propriedades dos tokens (is_stop, is_punct):

Este	True	False
é	True	False
sem	True	False
dúvida	False	False
o	True	False
pior	False	False
filme	False	False
que	True	False
eu	True	False
já	True	False
vi	False	False
.	False	True
E	True	False
acredite	False	False
em	True	False
mim	False	False
,	False	True
eu	True	False
vi	False	False
muitos	True	False
filmes	False	False
.	False	True
A	True	False
reviravolta	False	False
inacreditável	False	False
que	True	False
o	True	False
filme	False	False
faz	True	False
-	False	True
passando	False	False
de	True	False
um	True	False
extremamente	False	False
mau	False	False
filme	False	False
"	False	True
Formas	False	False
de	True	False
vida	False	False
alienígenas	False	False
habitam	False	False
a	True	False
terra	False	False
"	False	True
,	False	True
com	True	False
um	True	False
filme	False	False
que	True	False
tenta	False	False
espalhar	False	False
um	True	False
arquicristiano	False	False
"	False	True
O	True	False
dia	False	False
do	True	False
julgamento	False	False
está	True	False
próximo	True	False
,	False	True
buscar	False	False
Jesus	False	False
ou	True	False
queimar	False	False
por	True	False
toda	True	False
a	True	False
eternidade	False	False
em	True	False
as	True	False
dívidas	False	False
ardentes	False	False
do	True	False
inferno	False	False
"	False	True
mensagem	False	False
-	False	True
deixou-me	False	False
atordoado	False	False
depois	True	False
de	True	False
ter	True	False
sido	False	False
atormentado	False	False
por	True	False
85	False	False
minutos	False	False
.	False	True
Até	True	False
mesmo	True	False
os	True	False
cristãos	False	False
religiosos	False	False
devem	True	False
se	True	False
envergonhar	False	False
ou	True	False
ficar	False	False
furiosos	False	False
ao	True	False
ver	True	False
suas	True	False
crenças	False	False
postadas	False	False
dessa	True	False
maneira	False	False
.	False	True
Eu	True	False
não	True	False
sabia	False	False
o	True	False
que	True	False
fazer	True	False
comigo	False	False
quando	True	False
assisti	False	False
a	True	False
atuação	False	False
horrível	False	False
que	True	False
poderia	False	False
ter	True	False
sido	False	False
realizada	False	False
por	True	False
crianças	False	False
de	True	False
7	False	False
anos	False	False
de	True	False
idade	False	False
.	False	True
Simplesmente	False	False
repugnante	False	False
.	False	True
Eu	True	False
não	True	False
sou	True	False
cristão	False	False
nem	True	False
muito	True	False
religioso	False	False
.	False	True
Mas	True	False
se	True	False
eu	True	False
estivesse	False	False
,	False	True
não	True	False
teria	False	False
mais	True	False
medo	False	False
do	True	False
Inferno	False	False
.	False	True
Rich	False	False
Christiano	False	False
mostrou	False	False
ser	True	False
algo	True	False
muito	True	False
pior	False	False
.	False	True

Tokens filtrados (sem stopwords e pontuação):

dúvida
pior
filme
vi
acredite
mim
vi
filmes
reviravolta
inacreditável
filme
passando
extremamente
mau
filme
Formas
vida
alienígenas
habitam
terra
filme
tenta
espalhar
arquicristiano
dia
julgamento
buscar
Jesus
queimar
eternidade
dívidas
ardentes
inferno
mensagem
deixou-me
atordoado
sido
atormentado
85
minutos
cristãos
religiosos
envergonhar
ficar
furiosos
crenças
postadas
maneira
sabia
comigo
assisti
atuação
horrível
poderia
sido
realizada
crianças
7
anos
idade
Simplesmente
repugnante
cristão
religioso
estivesse
teria
medo
Inferno
Rich
Christiano
mostrou
pior

Número de stopwords: 74
Número de pontuação: 19

# Detecção de sentenças

As sentenças detectadas pelo modelo ficam armazenadas no atributo `.sents` do objeto `Doc`:

In [12]:
doc = nlp("Eu estarei em Recife próxima semana. Será que levo roupa para frio?")
for sent in doc.sents:
    print(sent)

Eu estarei em Recife próxima semana.
Será que levo roupa para frio?

### Exercício

1. Quantas sentenças existem no texto armazenado na variável `review`?

2. Quais são essas sentencas?

In [13]:
# sua resposta\
print("Sentenças: ")
for ex_sent in news.sents:
  print(ex_sent)

print("\nQuantidade de sentenças: ")
len(list(news.sents))

Sentenças:
Este é sem dúvida o pior filme que eu já vi.
E acredite em mim, eu vi muitos filmes.
A reviravolta inacreditável que o filme faz - passando de um extremamente mau filme "Formas de vida alienígenas habitam a terra", com um filme que tenta espalhar um arquicristiano "
O dia do julgamento está próximo, buscar Jesus ou queimar por toda a eternidade em as dívidas ardentes do inferno "mensagem - deixou-me atordoado depois de ter sido atormentado por 85 minutos.
Até mesmo os cristãos religiosos devem se envergonhar ou ficar furiosos ao ver suas crenças postadas dessa maneira.
Eu não sabia o que fazer comigo quando assisti a atuação horrível que poderia ter sido realizada por crianças de 7 anos de idade.
Simplesmente repugnante.
Eu não sou cristão nem muito religioso.
Mas se eu estivesse, não teria mais medo do Inferno.
Rich Christiano mostrou ser algo muito pior.

Quantidade de sentenças:

10

## POS tagging

Como vimos acima, ao submeter uma string ao modelo, o spacy aplica todo o pipeline de PLN ao texto, incluindo o processo de POS Tagging:

In [14]:
doc = nlp("Eu estarei em Recife próxima semana. Será que levo roupa para frio?")
for token in doc:
    print(token.text, token.pos_)

Eu PRON
estarei VERB
em ADP
Recife PROPN
próxima ADJ
semana NOUN
. PUNCT
Será VERB
que SCONJ
levo NOUN
roupa NOUN
para ADP
frio NOUN
? PUNCT

Esses rótulos podem ser um pouco difíceis de interpretar... O que significa `PROPN`? e `ADP`? Use a função `explain` para obter as respostas:

In [15]:
print(spacy.explain('PROPN'))
print(spacy.explain('ADP'))

proper noun
adposition

Observe que o texto (label) é sempre armazenado em um atributo com `_` no fim, pois o spaCy armazena internamente tudo na forma de hashes, para tornar o código mais eficiente:

In [16]:
for token in doc[:10]:
    print(token.text, token.pos)

Eu 95
estarei 100
em 85
Recife 96
próxima 84
semana 92
. 97
Será 100
que 98
levo 92

### Exercício

Retorne a lista de todas as POS Tags da variável `review` como uma lista de tuplas (word, pos) para cada token no texto. Quais as tags mais frequentes?

Dica: você pode utilizar um `pandas.DataFrame` para facilitar as contagens

In [17]:
# sua resposta

# Certifique-se de que 'news' foi processado a partir do 'review'
# Se 'news' não estiver definido, você precisaria rodar a célula f6Cvtyplksh- novamente
news = nlp(review)

# 1. Extrair as POS Tags como uma lista de tuplas (word, pos)
pos_tags_list = [(token.text, token.pos_) for token in news]

# 2. Criar um pandas.DataFrame
df_pos = pd.DataFrame(pos_tags_list, columns=['Token', 'POS_Tag'])

# 3. Analisar a distribuição das categorias (tags mais frequentes)
print("DataFrame com Tokens e suas POS Tags:")
display(df_pos.head())

print("\nFrequência das POS Tags:")
display(df_pos['POS_Tag'].value_counts())

DataFrame com Tokens e suas POS Tags:

    Token POS_Tag
0    Este    PRON
1       é     AUX
2     sem     ADP
3  dúvida    NOUN
4       o     DET

Frequência das POS Tags:

POS_Tag
NOUN     28
VERB     25
ADP      17
PUNCT    16
DET      16
PRON     14
ADJ      12
ADV      10
AUX       9
PROPN     6
CCONJ     5
SCONJ     4
NUM       3
Name: count, dtype: int64

## Lemmatization <a id='lemma'></a>

O spaCy não disponibiliza muitos detalhes de escolha de algoritmos para Lemmatization, o que funciona bem para a maioria dos casos, diferentemente do NLTK:

In [18]:
for token in doc:
    print(token.text, token.lemma_)

Eu eu
estarei estar
em em
Recife Recife
próxima próximo
semana semana
. .
Será ser
que que
levo levo
roupa roupa
para para
frio frio
? ?

## Named entity recognition (NER) <a id='ner'></a>

Named entity recognition (NER) é uma das principais tarefas em projetos de recuperação e extração de informação em textos. Muitas tarefas se iniciam a partir da detecção de entidades nomeadas, como a extração de relações por exemplo.

Em NER, as diferentes entidades nomeadas extraídas são agrupadas por tipo. Por exemplo, "pessoa", "organização", "local", "país" etc. No spaCy, existem muitos [tipos diferentes](https://spacy.io/api/annotation#named-entities) de entidades nomeadas que ele pode extrair com modelos pré-treinados.

As entidades nomeadas no spaCy estão disponíveis como propriedade `ents` de um` Doc`. O `.label_` nos diz o tipo de entidade nomeada.

In [19]:
doc = nlp("Eu estarei em Recife próxima semana. Será que levo roupa para frio?")
for ent in doc.ents:
    print(ent.text,ent.label_)

Recife LOC

In [20]:
doc = nlp("Geraldo Júlio é o prefeito de Recife.")
for ent in doc.ents:
    print(ent.text,ent.label_)

Geraldo Júlio PER
Recife LOC

In [21]:
#explain também funciona para entidades
spacy.explain('LOC')

'Non-GPE locations, mountain ranges, bodies of water'

### Exercício 1

Extraia todas as entidades nomeadas da variável `review`.

In [22]:
doc = nlp(review)
for ent in doc.ents:
    print(ent.text,ent.label_)

Jesus PER
Inferno MISC
Rich Christiano PER

### Exercício 2
Utilizar a lib do python `wikipedia`, para baixar o conteúdo da página referente ao presidente Bolsonaro no wikipedia em português, e analise quais as entidades presentes nas 10 primeiras sentenças do texto.

In [23]:
!pip install wikipedia

Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.6.17)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (4.16.0)
Building wheels for collected packages: wikipedia
  Building wheel for wikipedia (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11678 sha256=2c8b555cc08996a46a04c9ebe5440b73f34d755057fe62e8eae29f6a027f3d35
  Stored in directory: /root/.cache/pip/wheels/63/47/7c/a9688349aa74d228ce0a9023229c6c0ac52ca2a40fe87679b8
Successfully built wikipedia
Installing collected packages: wikipedia
Successfully installed wikipedia-1.4.0

In [24]:
import wikipedia
wikipedia.set_lang("pt")
p = wikipedia.page("Jair Bolsonaro")

print(p.url)
print(p.title)

content = p.content

https://pt.wikipedia.org/wiki/Jair_Bolsonaro
Jair Bolsonaro

In [25]:
# sua resposta

## Visualização NER <a id='visualize-ner'></a>

O displaCy é uma extensão do spaCy para visualização do processo de PLN.

Após importar a lib `displacy`, podemos usar o método `render` sobre o `doc` criado.

In [26]:
from spacy import displacy

In [27]:
displacy.render(doc, style='ent', jupyter=True)

### Exercício

Utilize o `displacy` para visualizar as entidades encontradas em algumas das sentenças do conteúdo da página do wikipedia analisada no exercício anterior.

In [28]:
# sua resposta

## Parsing de Dependencia

A análise de dependência refere-se a desenhar os relacionamentos entre palavras individuais em uma frase. Assim como o NER, esse é um tópico bem importante em PLN.

In [29]:
for token in doc[:18]:
    print(token.text, token.dep_, token.head)

Este nsubj filme
é cop filme
sem case dúvida
dúvida nmod filme
o det filme
pior amod filme
filme ROOT filme
que obj vi
eu nsubj vi
já advmod vi
vi acl:relcl filme
. punct filme
E cc acredite
acredite advcl vi
em case mim
mim obl acredite
, punct acredite
eu nsubj vi

Utilizando o `displacy`:

In [30]:
displacy.render(doc, style='dep', jupyter=True)

In [31]:
# modificando a visualização
displacy.render(doc, style='dep', jupyter=True, options={"compact": True})

### Exercício

Crie uma lista para cada tipo de entidade no texto da wikipedia analisado, ou seja:
- texto (string)
- pos
- lemma
- se é uma stopword (`.is_stop`)
- se é pontuação (`.is_punct`)
- se é um número (`.like_num`)
- a relação de dependência (`.dep_`)

Utilize as listas criadas para criar um `pandas.DataFrame`, e analise a distribuição das categorias registradas.

In [32]:
doc = nlp(content)
tokens = [token.text for token in doc]

# resposta

## Word vectors e similaridade <a id='vectors'></a>

Os modelos do spaCy em sua versão reduzida (`sm`), não incluem word vectors completos, de modo que é possível obter uma aproximação dessas distâncias. Caso se queira utilizar algo mais preciso, é recomendado utilizar os modelos `lg` (large) ou ainda carregar outros dicionários de vetores, como o word2vec, fastText, etc. O `gensim` é uma biblioteca que auxilia o uso de tais dicionários.

In [33]:
w1 = nlp('gato')
w2 = nlp('cachorro')
w3 = nlp('presidente')

In [34]:
w1.similarity(w2)

/tmp/ipykernel_1169/108627858.py:1: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  w1.similarity(w2)

0.4350873529911041

In [35]:
w2.similarity(w3)

/tmp/ipykernel_1169/754946760.py:1: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  w2.similarity(w3)

0.45244744420051575

Similaridade entre textos:

In [36]:
doc_review = nlp(review)
doc_wiki   = nlp(content)

doc_review.similarity(doc_wiki)

/tmp/ipykernel_1169/3082622120.py:4: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  doc_review.similarity(doc_wiki)

0.8289863467216492